import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";

// تعریف فونت محلی با استفاده از next/font/local
const myLocalFont = localFont({
  src: "./assets/fonts/YekanBakhFaNum-VF.ttf", // مسیر فونت
  variable: "--font-my-local", // نام متغیر CSS برای فونت
});

// تعریف متادیتا برای صفحه
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      {/* بدنه‌ی صفحه با جهت‌دهی راست‌به‌چپ (RTL) و استایل‌های کلی */}
      <body
        dir="rtl"
        className={`${myLocalFont.variable} antialiased text-slate-50 bg-slate-900 font-my-local h-[100vh]`}
      >
        {/* هدر صفحه */}
        <Header />
        {/* بخش اصلی محتوای صفحه */}
        <main className="flex-grow p-4">{children}</main>
      </body>
    </html>
  );
}
